### ISSUE TITLE
pos+rot entangled in id+exp

### ISSUE THREAD

**Issue by iperov** [wang-zidu/3DDFA-V3#4]
https://github.com/wang-zidu/3DDFA-V3/assets/8076202/129fa44f-00cc-4d98-b0c5-7b4d9d085fd7

two green dots are upper and lower bound of base face mesh model transformed only with rotation+pos, without id+exp.
As we can see it does not move correctly, so we can conclude that residual movements are entagled in id+exp.

**Comment by wang-zidu** [comment]
Hello, I have conducted a check and the issue you mentioned may not exist. I suggest you further check the code or try more visualization. The upper and lower vertices should be obtained from a mesh that has not undergone rotation to get the corresponding indices, and then the appropriate transformations should be applied (as shown in the second column of the figure below), rather than simply extracting the maximum and minimum coordinates in the y-direction directly from the results (which I assume you did, as shown in the third column of the figure below).
![issue4](https://github.com/wang-zidu/3DDFA-V3/assets/164336695/14eb75fe-7665-4045-8439-a48aeece8330)
